language: php

sudo: false

php:
  - '7.1'
  - '7.2'
  - nightly

script: ./vendor/bin/phpunit

before_script:
    - pwd
    - php -v
    - composer install --no-interaction --prefer-source
    - echo "Test file" > ./tests/test.txt
    - ls -l ./tests